title: Interactive Graphics & Engineering Lab

baseurl: 'https://cgenglab.github.io/labpage/'

copyright: '&copy; Nobuyuki Umetani {year}'

publishDir: docs

# Get last modified date for content from Git?
enableGitInfo: false

# Default language to use (if you setup multilingual support)
defaultContentLanguage: ja

# Set `true` for Chinese/Japanese/Korean languages.
hasCJKLanguage: true


defaultContentLanguageInSubdir: true

# Workaround for https://github.com/gohugoio/hugo/issues/5687
removePathAccents: false

summaryLength: 30

# Number of items per page in paginated lists.
paginate: 10

enableEmoji: true

enableRobotsTXT: true

footnotereturnlinkcontents: <sup>^</sup>

ignoreFiles:
  - \.ipynb$
  - .ipynb_checkpoints$
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$


# Workaround Hugo publishing taxonomy URLs as plurals - consistently use singular across Academic.  
permalinks:
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  publication_types: '/publication-type/:slug/'

outputs:
  home:
    - HTML
    - RSS
    - JSON
    - WebAppManifest
  section:
    - HTML
    - RSS

mediaTypes:
  application/manifest+json:
    suffixes:
      - webmanifest

outputFormats:
  WebAppManifest:
    mediaType: application/manifest+json
    rel: manifest

# Configure the Markdown renderer.    
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: false
  tableOfContents:
    startLevel: 2
    endLevel: 3

imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart

taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors

related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: title
      weight: 60
    - name: summary
      weight: 50
    - name: tags
      weight: 80
    - name: categories
      weight: 70
    - name: authors
      weight: 20

module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy-cms/v5
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy/v5

security:
  funcs:
    getenv:
      - ^HUGO_
      - ^WC_
